{ config, lib, pkgs, modulesPath, inputs, ... }:
{
    environment.systemPackages = with pkgs; [
        niri
        obsidian
        polkit_gnome
        gparted
        ntfs3g
        exfatprogs
        dosfstools
        btrfs-progs
        xfsprogs
        hfsprogs
        f2fs-tools
        jfsutils
        localsend
        hyfetch
        fastfetch
        btop
        wget
        curl
        librewolf
        vscode
        xwayland-satellite
        mako
        gnome-keyring
        xdg-desktop-portal-gtk
        xdg-desktop-portal-gnome
        fuzzel
        kdePackages.polkit-kde-agent-1
        xdg-utils
        nautilus
        inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
        supersonic-wayland
        vesktop
        fractal
        mumble
        bitwarden-desktop
        blender
        blockbench
        prismlauncher
        vlc
        handbrake
        obs-studio
        losslesscut-bin
        remmina
        syncthing
        ungoogled-chromium
        bluebubbles
    ];
}
